version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: vistrace-postgres
    environment:
      POSTGRES_DB: vistrace
      POSTGRES_USER: vistrace_user
      POSTGRES_PASSWORD: vistrace_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./vistrace-backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vistrace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vistrace_user -d vistrace"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Service
  backend:
    build:
      context: ./vistrace-backend
      dockerfile: Dockerfile
    container_name: vistrace-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://vistrace_user:vistrace_password@postgres:5432/vistrace
      # Optional API keys - add your own
      # IPSTACK_API_KEY: your_ipstack_key_here
      # IPINFO_TOKEN: your_ipinfo_token_here
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vistrace-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # Required for traceroute to work
    cap_add:
      - NET_RAW
      - NET_ADMIN
    # Install traceroute in container
    command: >
      sh -c "
        if ! command -v traceroute >/dev/null 2>&1; then
          apk add --no-cache iputils traceroute
        fi &&
        npm start
      "

  # Frontend React App
  frontend:
    build:
      context: ./vistrace-app
      dockerfile: Dockerfile
    container_name: vistrace-frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vistrace-network

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vistrace-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vistrace.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - vistrace-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  vistrace-network:
    driver: bridge
